<KivyCustomClassFields>: # inherits from KivyCustomClassButtons
	orientation: 'vertical'
	TextInput:
		id: first_text_input
		size_hint_y: 0.13
		text: "First TextInput"
		multiline: False
		on_text_validate: root.printFirstText()
	TextInput:
		id: second_text_input
		size_hint_y: 0.13
		text: "Second TextInput"
		multiline: False
		on_text_validate: root.printSecondText()
#    KivyCustomClassButtons: # WARNING: does causes double display !
#        id: kivy_custom_class_buttons