# Next import instruction avoids importing the class in the app python file, import
# which will be removed by Pycharm when optimizing the import !
#: import KivyCustomClassButtons kivycustomclassbuttons.KivyCustomClassButtons

<KivyCustomClassButtons>:
    orientation: 'vertical'
    Button:
        id: next_track
        text: "Next Track"
        on_press: root.nextTrack()
    Button:
        id: previous_track
        text: "Previous Track"
        on_press: root.previousTrack()
