# Next import instruction avoids importing the class in the app python file, import
# which will be removed by Pycharm when optimizing the import !
#: import KivyCustomClassGUI kivycustomclassgui.KivyCustomClassGUI

<KivyCustomClassFieldsButtons>:
	orientation: 'vertical'
    TextInput:
        text: "Next Text"
    TextInput:
        id: previous_track
        text: "Previous Text"
    KivyCustomClassGUI:
