<SecondWindow>:
	name: "second"
	secondButton: second_button

    BoxLayout:
		orientation: "vertical"

        Button:
            text: "Go Back ..."
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "right"
        Button:
            id: second_button
            text: 'Do second work'
            on_press: root.doSecondWork()
